catalog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^books/$', views.BookListView.as_view(), name='books'),
url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book-update'),
url(r'^book/create/$', views.BookCreate.as_view(), name='book-create'),
url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
url(r'^author/create/$', views.AuthorCreate.as_view(), name='author-create'),
url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author-update'),
url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author-delete'),
url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
url(r'^loanedbook/$', views.LoanedBooksListView.as_view(), name='all-borrowed'),
url(r'^book/(?P<pk>[-\w+]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
]

locallibrary/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                url(r'^admin/', admin.site.urls),
                url(r'^catalog/', include('catalog.urls')),
                url(r'^$', RedirectView.as_view(url = 'catalog/', permanent=True)),
                url(r'^accounts/', include('django.contrib.auth.urls')),
                ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid

# Create your models here.
class Genre(models.Model):
    """
    Genre for the books like Science fiction, Horror etc.
    """
    name = models.CharField(max_length = 200, help_text = "Enter a Book Genre eg. Science Fiction, Poetry etc.")

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    #ForeignKey used because book can only have on author but authors can have many books
    summary = models.TextField(max_length=1000, help_text="Enter a brief summary for the book here.")
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse ('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    """
    Model representing a sepcific copy of a book (i.e. that can be borrowed from the library)
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular copy of the book")
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='d', help_text="Book Availability")

    @property
    def is_overdue(self):
        if date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_as_returned", "Set book as returned"),)

    def __str__(self):
        return '%s (%s)' % (self.id, self.book.title)


class Author(models.Model):
    "Model representing an Author"
    first_name = models.CharField(max_length=100, help_text="Author's First Name")
    last_name = models.CharField(max_length=100, help_text="Author's Last Name")
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):

        return reverse ('author-detail', args=[str(self.id)])

    def get_books(self):
        book_list = Book.objects.filter(author__id=self.id)
        return (book_list)

    def __str__(self):

        return '%s, %s' %(self.last_name, self.first_name)

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text = "Enter a date between now and 4 weeks (default 3).")
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid Date - Renewal in Past'))

        if data > datetime.date.today() + datetime.timedelta(weeks =4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import permission_required
import datetime
from .forms import RenewBookForm

# Create your views here.




def index(request):
        num_books = Book.objects.all().count()
        num_instances = BookInstance.objects.all().count()
        num_instances_available = BookInstance.objects.filter(status__exact='a').count()
        num_authors = Author.objects.count()
        page_title = "Index of Local Library"
        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1
        context = {
            'num_books':num_books, 'num_instances':num_instances,
            'num_instances_available':num_instances_available, 'num_authors':num_authors,
            'page_title':page_title, 'num_visits':num_visits,
            }
        return render(request, 'index.html', context)


class BookListView(generic.ListView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['page_title'] = 'Book List'
        return context

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context['page_title'] = 'Author List'
        return context

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class LoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_as_returned'
    template_name = 'catalog/loaned_book_list.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_as_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == "POST":
        form = RenewBookForm(request.POST)

        if form.is_valid():
            new_date = form.cleaned_data['renewal_date']
            book_inst.due_back = new_date
            book_inst.save()

            return HttpResponseRedirect(reverse('all-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial = {'renewal_date': proposed_renewal_date})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death':'12/10/2016,'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(CreateView):
    model = Book
    fields = '__all__'

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'

catalog/templates/catalog/author_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<h1> Delete Author</h1>

<p> Are you sure you want to delete the author: {{author}}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete" />
</form>





{% endblock content %}

catalog/templates/catalog/author_detail.html
{% extends "base.html" %}

  {% block title %}{{author.first_name}} {{author.last_name}} {% endblock title %}

{% block content %}

    <h1>Author Details </h1>
      <p><strong>Name: </strong>{{author.first_name}} {{author.last_name}}</p>
      <p><strong>Date of Birth: </strong>{{author.date_of_birth}}</p>
        {% if author.get_books %}

        <div class="list-group">
            <p class="list-group-item list-group-item-info mylistheader">
              {% if author.get_books.count > 1%} <strong>This author has written {{author.get_books.count}} books</strong>
              {% else %}
              <strong>This author has written {{author.get_books.count}} book</strong>
              {% endif %}
            </p>

              {% for book in author.get_books %}
                <a href="{{book.get_absolute_url}}" class="list-group-item list-group-item-warning">{{book}}</a>
              {% endfor %}
        </div>
        {% else %}
          <p class="alert alert-danger"><strong>We have no books from this author.</strong></p>
        {% endif %}

{% endblock content %}

catalog/templates/catalog/author_form.html
{% extends "base.html" %}
{% block content %}

<h1> Update Author Here</h1>

<form action="?next={{request.path}}" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" class="btn btn-default" value="Submit" />
</form>

{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends "base.html" %}

{% block title %} {{page_title}} {% endblock title %}

{% block content %}

<h1>Author List</h1>

   {% if author_list %}
   <table class="table table-bordered table-hover">
          <tr >
          <th class="table-head">Author</th>
          <th class="table-head">Update</th>
          <th class="table-head">Delete</th>
          </tr>

     {% for author in author_list %}
    <tr>
       <td><a href="{{ author.get_absolute_url }}" class="author-list">{{ author.first_name }} {{author.last_name}}
       <span class="badge">{{author.get_books.count}}</span>
       </a>
       </td>
       <td><a href="{% url 'author-update' author.id %}" class="btn btn-default">
         <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
       </a>
     </td>
       <td><a href="{% url 'author-delete' author.id %}" class="btn btn-danger">
         <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
       </a>
     </td>
    </tr>
     {% endfor %}

   </table>
   {% else %}
     <p>There are no Auhors in our records.</p>
   {% endif %}


{% endblock content %}

catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

  {% block title %} {{page_title}} {% endblock title %}

{% block content %}

<h1>Title: {{ book.title }}</h1>

 <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
 <p><strong>Summary:</strong> {{ book.summary }}</p>
 <p><strong>ISBN:</strong> {{ book.isbn }}</p>
 <p><strong>Language:</strong> {{ book.language }}</p>
 <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

 <div style="margin-left:20px;margin-top:20px">
   <h4>Copies</h4>

   {% for copy in book.bookinstance_set.all %}
   <hr>
   <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
   {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
   <p><strong>Imprint:</strong> {{copy.imprint}}</p>
   <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
   {% endfor %}
 </div>

{% endblock content %}

catalog/templates/catalog/book_form.html
{% extends "base.html" %}
{% block content %}

<h1> Update Book to Library </h1>

  <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" class="btn btn-default" value="Submit" />


  </form>





{% endblock content %}

catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block title %} {{page_title}} {% endblock title %}

{% block content %}

<h1>Book List</h1>

   {% if book_list %}
   <ul>

     {% for book in book_list %}
     <li>
       <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
       <a href="{% url 'book-update' book.id %}">Update</a>
     </li>
     {% endfor %}

   </ul>
   {% else %}
     <p>There are no books in the library.</p>
   {% endif %}


{% endblock content %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base.html" %}
{% block content %}

      <h1> Renew: {{bookinst.book.title}}</h1>
      <p> Borrower: {{bookinst.borrower.first_name}} {{bookinst.borrower.last_name}}</p>
      <p {% if bookinst.is_overdue %} class = "text-dander"{% endif %}>Due Date: {{bookinst.due_back}}</p>

          <form action="" method="POST">
            {% csrf_token %}
            <table>
              {{form}}
            </table>
            <input type="submit" value="SUBMIT"/>
          </form>
{% endblock content %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

  {% block title %} Borrower {{user.last_name}} {% endblock title %}

{% block content %}

<h1>Borrowed books</h1>

   {% if bookinstance_list %}
   <ul>

     {% for bookinst in bookinstance_list %}
     <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
       <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
     </li>
     {% endfor %}
   </ul>

   {% else %}
     <p>There are no books borrowed.</p>
   {% endif %}

{% endblock content %}

catalog/templates/catalog/loaned_book_list.html
{% extends 'base.html' %}

{% block content %}

  <h1>All Borrowed Books</h1>
    {% if bookinstance_list %}
      {% for bookinst in bookinstance_list %}

      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
      <a href="{{bookinst.book.get_absolute_url}}">{{bookinst.book.title}}</a>
           {{bookinst.due_back}} -|- {{bookinst.borrower.first_name}} {{bookinst.borrower.last_name}}
           {% if perms.catalog.can_mark_as_returned %}<a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
           {% endif %}
      </li>


      {% endfor %}
    {% endif %}
{% endblock content %}
 